### ISSUE TITLE
Fix Steam SSO login identifier parsing

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#97]
Steam switched their community URLs to use HTTPS, currently breaking the SSO login parsing. This should be fixed ASAP.

**Comment by MorpheusXAUT** [comment]
The initial Steam OpenID provider URL was HTTP-only up until a few days ago, at least the identity returned definitely was (see https://github.com/MorpheusXAUT/slotlist-backend/blob/master/src/shared/services/SteamService.ts#L62). Since they've changed that now, the verification regex failed, probably should have included an optional `s` to start out with, oops 😬

**Comment by Regner** [comment]
Ahhhhhhh
